[package]
name = "frutiger-compositor"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
smithay.workspace = true
wayland-server.workspace = true
calloop.workspace = true
tracing.workspace = true
thiserror.workspace = true
anyhow.workspace = true
winit.workspace = true
frutiger-render.workspace = true
frutiger-config.workspace = true
