[package]
name = "frutiger-visual-tests"
version.workspace = true
description.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
adw = { version = "0.8.1", package = "libadwaita", features = ["v1_4"] }
anyhow.workspace = true
gtk = { version = "0.10.3", package = "gtk4", features = ["v4_12"] }
frutiger = { version = "0.1.0", path = ".." }
frutiger-config = { version = "0.1.0", path = "../frutiger-config" }
smithay.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
